# General Configuration

url: http://natansh.in
top_title: Natansh Verma
title: NV
expanded_title: NATANSH VERMA
subtitle: Simplicity is the ultimate sophistication

date_format: "ordinal"

subscribe_rss: /atom.xml
email: natansh@gmail.com

# Jekyll Configuration
root: /

paginate: 11
titlecase: true
permalink: pretty
excerpt_separator: ""

highlighter: pygments

markdown: kramdown 

exclude: [CHANGELOG.md, README.md, generate_sprites.rb]

safe: true
lsi: false
